export { default as AppComponent } from '../app/app.component'
export { default as Home } from './Home'
export { default as Foo } from './Foo'
export { default as Bar } from './Bar'
export { default as Menu } from './Menu'
export { default as Test } from './test'
export { default as Ajax } from './Ajax'