export { default as AppComponent } from '../app/app.component'
export { default as Home } from './pages/Home'
export { default as Foo } from './pages/Foo'
export { default as Bar } from './pages/Bar'
export { default as Test } from './test'
export { default as TestPaginate } from './testPaginate.js'
export { default as Ajax } from './pages/Ajax'